### PR TITLE
add batch mode

### PR DESCRIPTION
**Pull request by mousetail**
Adds a batch mode to allow running large numbers of bots against each-other without needing to restart the runners each time.

Is about 4-6 times faster than running the games separately.

Pretty quick and dirty for now.

It's still taking about 0.35 seconds per game which I feel is more than it should be. Might be more inefficiencies elsewhere

Sample timing:
```
Setup took 46.287893ms
Game took 303.852227ms
```

### CODE REVIEW

**Comment by outkine** [comment]
Thank you for this. I would prefer an API where you pass in a JSON array of the form `[{"red": "...", "blue": "...", "seed": "(optional)"}]` instead of passing with newlines, what do you think?

**Comment by mousetail** [comment]
I choose this so I can continuously stream in more data and it would keep running it. That way I can choose what bot to go next based on the result of the previous match.

**Comment by outkine** [comment]
That makes sense. Do you think that it would be useful to have the same configurable battle display as in term mode for each game in batch mode?

**Comment by mousetail** [comment]
I'm open to more output options. I restricted it to just the winner because outputting is slow so it would save a little bit of time. But there is no harm in allowing more options.

It would need some thought how to separate the output from different games properly though.

**Comment by outkine** [comment]
That's true and is probably out of scope for now. Let me know if the changes in 98156a8d7b25e66a6c19c30e54032e0908927950 look good!

**Comment by mousetail** [comment]
looks fine. I left 2 minor comments but feel free to ignore them.

**Comment by outkine** [comment]
Merged manually with 1ad560b315fa28fb9a7c34f94f93690ed0daa568

**Pull request closed without merging**
